// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9EDU85g3u3IEXd2dOMF4KfU7VJu1tZFI',
    appId: '1:747592026135:web:e27654e1610761c7863452',
    messagingSenderId: '747592026135',
    projectId: 'flutter-chat-app-98438',
    authDomain: 'flutter-chat-app-98438.firebaseapp.com',
    storageBucket: 'flutter-chat-app-98438.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpbiPYMHP7a8un6bYbA3yvue-DpTmJxMQ',
    appId: '1:747592026135:android:7a5d7d8003fab4be863452',
    messagingSenderId: '747592026135',
    projectId: 'flutter-chat-app-98438',
    storageBucket: 'flutter-chat-app-98438.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiJtTQkGZx1acoJASmyqLAm4HAEbIwVkU',
    appId: '1:747592026135:ios:445252ef7301d291863452',
    messagingSenderId: '747592026135',
    projectId: 'flutter-chat-app-98438',
    storageBucket: 'flutter-chat-app-98438.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiJtTQkGZx1acoJASmyqLAm4HAEbIwVkU',
    appId: '1:747592026135:ios:ef3a53be1e2731c4863452',
    messagingSenderId: '747592026135',
    projectId: 'flutter-chat-app-98438',
    storageBucket: 'flutter-chat-app-98438.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
