// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsQhxMneaJsILlccuvmoup4ggi78DEP4Y',
    appId: '1:350579309222:web:8d8192fae7c9f2763e5267',
    messagingSenderId: '350579309222',
    projectId: 'tiktok-clone-58efc',
    authDomain: 'tiktok-clone-58efc.firebaseapp.com',
    storageBucket: 'tiktok-clone-58efc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZGsWMUHLLfcqaslnEHf1ivVC79Fo7swo',
    appId: '1:350579309222:android:687b4807d2e4cc1a3e5267',
    messagingSenderId: '350579309222',
    projectId: 'tiktok-clone-58efc',
    storageBucket: 'tiktok-clone-58efc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGc153h6weSXIuRXbXMr0UNGmbDAWEl58',
    appId: '1:350579309222:ios:cf35cedc8153e0513e5267',
    messagingSenderId: '350579309222',
    projectId: 'tiktok-clone-58efc',
    storageBucket: 'tiktok-clone-58efc.appspot.com',
    iosClientId: '350579309222-3q5akktvefcdggohngoqnmulra1eg2lt.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGc153h6weSXIuRXbXMr0UNGmbDAWEl58',
    appId: '1:350579309222:ios:b4c9c946cf05fbdb3e5267',
    messagingSenderId: '350579309222',
    projectId: 'tiktok-clone-58efc',
    storageBucket: 'tiktok-clone-58efc.appspot.com',
    iosClientId: '350579309222-h5u06jdg2bhr2tjpq60rqg4ggml9n1p5.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone.RunnerTests',
  );
}
