// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLmQvrDdXZ6j-48ZQ7JM1YnquSJ8e52yY',
    appId: '1:1009372582456:web:950b36e90e04c447578ccd',
    messagingSenderId: '1009372582456',
    projectId: 'signin-example-19234',
    authDomain: 'signin-example-19234.firebaseapp.com',
    storageBucket: 'signin-example-19234.appspot.com',
    measurementId: 'G-Z0NZQEGFC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVObCewrYZXbrTOnHa82bndVF4vwsH4fY',
    appId: '1:1009372582456:android:e22e17cd71a208e4578ccd',
    messagingSenderId: '1009372582456',
    projectId: 'signin-example-19234',
    storageBucket: 'signin-example-19234.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzl0IcolO6epBA39fCGn1o_Kr8ufSQXhA',
    appId: '1:1009372582456:ios:ff82a08910ab3af1578ccd',
    messagingSenderId: '1009372582456',
    projectId: 'signin-example-19234',
    storageBucket: 'signin-example-19234.appspot.com',
    androidClientId: '1009372582456-r3bdag52hj1c7lhfjcr0tseed1j40cka.apps.googleusercontent.com',
    iosClientId: '1009372582456-1ciuhg36mgoi0d9s1asuutcpvlhd9gc3.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleSignin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzl0IcolO6epBA39fCGn1o_Kr8ufSQXhA',
    appId: '1:1009372582456:ios:db6ed04c4df518dc578ccd',
    messagingSenderId: '1009372582456',
    projectId: 'signin-example-19234',
    storageBucket: 'signin-example-19234.appspot.com',
    androidClientId: '1009372582456-r3bdag52hj1c7lhfjcr0tseed1j40cka.apps.googleusercontent.com',
    iosClientId: '1009372582456-mp11prae68441acg5c9rss842v6cal1q.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleSignin.RunnerTests',
  );
}
